const std = @import("std");
pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const allocator = init.arena.allocator();
    var args_it = try std.process.Args.Iterator.initAllocator(init.minimal.args, allocator);
    defer args_it.deinit();
    _ = args_it.next(); // Skip program name
    const source_dir = args_it.next() orelse {
        std.debug.print("Usage: generate-templates <source_dir> <output_file>\n", .{});
        return error.InvalidArgs;
    };
    const output_file = args_it.next() orelse {
        std.debug.print("Usage: generate-templates <source_dir> <output_file>\n", .{});
        return error.InvalidArgs;
    };
    var output = try std.ArrayList(u8).initCapacity(allocator, 4096);
    defer output.deinit(allocator);
    try output.appendSlice(allocator, "// Generated file - DO NOT EDIT MANUALLY\n");
    try output.appendSlice(allocator, "// This file is automatically generated by Spider's generateEmbeddedTemplates\n");
    const source_dir_line = try std.fmt.allocPrint(allocator, "// Source directory: {s}\n\n", .{source_dir});
    defer allocator.free(source_dir_line);
    try output.appendSlice(allocator, source_dir_line);
    try output.appendSlice(allocator, "pub const EmbeddedTemplates = struct {\n\n");
    const cwd = std.Io.Dir.cwd();
    var dir = try cwd.openDir(io, source_dir, .{ .iterate = true });
    defer dir.close(io);
    var walker = try dir.walk(allocator);
    defer walker.deinit();
    var template_count: usize = 0;
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".html") and
            !std.mem.endsWith(u8, entry.path, ".md")) continue;
        var field_name_buf: [256]u8 = undefined;
        const field_name = try generateFieldName(entry.path, &field_name_buf);
        const embed_path = entry.path;
        const line = try std.fmt.allocPrint(allocator, "    {s}: []const u8 = @embedFile(\"{s}\"),\n", .{ field_name, embed_path });
        defer allocator.free(line);
        try output.appendSlice(allocator, line);
        template_count += 1;
    }
    try output.appendSlice(allocator, "\n};\n");
    const out_file = try cwd.createFile(io, output_file, .{});
    defer out_file.close(io);
    var buffer: [4096]u8 = undefined;
    var writer: std.Io.File.Writer = .init(out_file, io, &buffer);
    try writer.interface.writeAll(output.items);
    try writer.interface.flush();
    std.debug.print("Ride the lightning — {d} templates forged in {s}\n", .{ template_count, output_file });
}

fn generateFieldName(path: []const u8, buffer: []u8) ![]const u8 {
    const no_ext = if (std.mem.endsWith(u8, path, ".html"))
        path[0 .. path.len - 5]
    else if (std.mem.endsWith(u8, path, ".md"))
        path[0 .. path.len - 3]
    else
        path;

    if (std.mem.indexOf(u8, no_ext, "views/")) |idx| {
        const after = no_ext[idx + "views/".len ..];
        const file = std.fs.path.basename(after);
        const before = no_ext[0..idx];
        const dir = std.fs.path.basename(before);

        if (dir.len == 0) {
            // Normalize full path after views/ — bills/index → bills_index
            var j: usize = 0;
            for (after) |c| {
                if (j >= buffer.len) break;
                buffer[j] = if (c == '/' or c == '-') '_' else c;
                j += 1;
            }
            return buffer[0..j];
        }

        if (std.mem.eql(u8, dir, file)) {
            return try std.fmt.bufPrint(buffer, "{s}", .{file});
        }
        if (file.len > 0 and file[0] >= 'A' and file[0] <= 'Z') {
            return try std.fmt.bufPrint(buffer, "{s}", .{file});
        }
        return try std.fmt.bufPrint(buffer, "{s}_{s}", .{ dir, file });
    }

    // shared/templates/
    var remaining = no_ext;
    if (std.mem.startsWith(u8, remaining, "shared/templates/")) {
        remaining = remaining["shared/templates/".len..];
    }
    var j: usize = 0;
    for (remaining) |c| {
        buffer[j] = if (c == '/' or c == '-') '_' else c;
        j += 1;
    }
    return buffer[0..j];
}
